# DEV
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=${DEV_DB_USER}
%dev.quarkus.datasource.password=${DEV_DB_PASSWORD}
%dev.quarkus.datasource.jdbc.url=${DEV_DB_URL}
%dev.quarkus.mailer.mock=false

# PROD
%prod.quarkus.http.port=${PORT:8080}
%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${PROD_DB_URL}?sslmode=require
%prod.quarkus.datasource.username=${PROD_DB_USER}
%prod.quarkus.datasource.password=${PROD_DB_PASSWORD}
%prod.quarkus.datasource.jdbc.max-size=10
%prod.quarkus.hibernate-orm.database.generation=none
%prod.quarkus.flyway.migrate-at-start=true

# PROD CORS
%prod.quarkus.http.cors.enabled=true
%prod.quarkus.http.cors.origins=https://cashflow-luzonni.vercel.app
%prod.quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH,OPTIONS
%prod.quarkus.http.cors.headers=Content-Type,Authorization,Accept,Origin,X-Requested-With
%prod.quarkus.http.cors.access-control-max-age=24H
%prod.quarkus.http.cors.access-control-allow-credentials=true

# TEST

%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.devservices.image-name=postgres:16
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.log.sql=true

# =======================================================

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true
quarkus.swagger-ui.always-include=true
quarkus.datasource.devservices.enabled=false

# Cors

%dev.quarkus.http.cors.enabled=true
%dev.quarkus.http.cors.origins=http://localhost:3000
%dev.quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,PATCH,OPTIONS
%dev.quarkus.http.cors.headers=Content-Type,Authorization,Accept,Origin,X-Requested-With
%dev.quarkus.http.cors.access-control-max-age=24H
%dev.quarkus.http.cors.access-control-allow-credentials=true

# MyAuth

auth.refresh-token.expiration-days=15
auth.access-token.expiration-minutes=15

# JWT

mp.jwt.verify.issuer=cashflow
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=accessToken
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem

# Resend

quarkus.mailer.host=smtp.resend.com
quarkus.mailer.port=465
quarkus.mailer.ssl=true
quarkus.mailer.username=resend
quarkus.mailer.password=${RESEND_API_KEY}
quarkus.mailer.from=onboarding@resend.dev
