package com.luzonni.cashflow.features.exception.dto;

public enum ErrorCode {

    NAME_RESERVED_BY_DELETED_ENTITY,
    ENTITY_ALREADY_EXISTS,
    ENTITY_NOT_FOUND,
    INVALID_OPERATION,
    REFRESH_TOKEN_INVALID,
    REFRESH_TOKEN_EXPIRED,
    UNAUTHORIZED,
    VALIDATION_ERROR,
    INVALID_VERIFICATION_TOKEN,
    EXPIRED_VERIFICATION_TOKEN,
    USER_ALREADY_EXISTS,
    USER_NOT_FOUND,
    RATE_ERROR_OPERATION,
    CURRENCY_NOT_SUPPORTED

}
